sudo: false 
dist: trusty
language: node_js
node_js:
 - "8.9.3"
cache:
  directories:
  - node_modules #Cache node_modules for faster builds
before_install:
- openssl aes-256-cbc -K $encrypted_745ce00b467b_key -iv $encrypted_745ce00b467b_iv -in envs.tar.enc -out envs.tar -d
- tar xvf envs.tar
install: 
- npm install
- npm run build
deploy:
  provider: azure_web_apps
  site: easypedweb
  skip_cleanup: true
  verbose: true