sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker build -t pedrocha/easymedweb .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master