sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
before_install:
  - openssl aes-256-cbc -K $encrypted_745ce00b467b_key -iv $encrypted_745ce00b467b_iv -in envs.tar.enc -out envs.tar -d
  - tar xvf envs.tar
  - docker build -t pedrocha/easymedweb .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master