dist: trusty
language: node_js
node_js:
- stable
before_script:
- npm install
before_deploy:
- npm run build
deploy:
  provider: azure_web_apps
before_install:
- openssl aes-256-cbc -K $encrypted_745ce00b467b_key -iv $encrypted_745ce00b467b_iv
  -in .env.test.enc -out .env.test -d
- openssl aes-256-cbc -K $encrypted_745ce00b467b_key -iv $encrypted_745ce00b467b_iv
  -in .env.prod.enc -out .env.prod -d
- openssl aes-256-cbc -K $encrypted_745ce00b467b_key -iv $encrypted_745ce00b467b_iv
  -in .env.dev.enc -out .env.dev -d
