dist: trusty
language: node_js
node_js:
- stable
before_script:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_745ce00b467b_key -iv $encrypted_745ce00b467b_iv -in envs.tar.enc -out envs.tar -d
- tar xvf envs.tar
deploy:
  provider: azure_web_apps
  site: easypedweb
  skip_cleanup: true
  verbose: true
