pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
- script: 
    echo $(FIREBASE_API_KEY)
- script: |
    echo 'FIREBASE_API_KEY=$(FIREBASE_API_KEY)' > .env.prod
    echo 'FIREBASE_AUTH_DOMAIN=$(FIREBASE_AUTH_DOMAIN)' >> .env.prod
    echo 'FIREBASE_DATABASE_URL=$(FIREBASE_DATABASE_URL)' >> .env.prod
    echo 'FIREBASE_PROJECT_ID=$(FIREBASE_PROJECT_ID)' >> .env.prod
    echo 'FIREBASE_STORAGE_BUCKET=$(FIREBASE_STORAGE_BUCKET)' >> .env.prod
    echo 'FIREBASE_MSG_SENDING_ID=$(FIREBASE_MSG_SENDING_ID)' >> .env.prod
    echo 'API_BASE_URL=$(API_BASE_URL)' >> .env.prod
    echo 'GOOGLE_ANALYTICS_ID=$(GOOGLE_ANALYTICS_ID)' >> .env.prod

- script: |
    npm install
    npm run build

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: easymedweb'
  inputs:
    azureSubscription: 'Visual Studio Enterprise: BizSpark (51b0ae85-b013-43f7-b1ea-104c47d3805c)'
    appType: webAppLinux
    WebAppName: 'easypedweb'
    RuntimeStack: 'NODE|8.11'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'



